#!/bin/bash

# Extract the Go archive to /usr/local
export VERSION=1.11 OS=linux ARCH=amd64 && \
	wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz && \
	sudo tar -C /usr/local -xzvf go$VERSION.$OS-$ARCH.tar.gz && \
	rm go$VERSION.$OS-$ARCH.tar.gz

# Set up the environment for Go
echo 'export GOPATH=$/usr/local/go' >> ~/.bashrc && \
	echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc && \ 
	source ~/.bashrc

# Install dep for dependency resolution
go get -u github.com/golang/dep/cmd/dep

# Repeat the installation on all of the compute nodes using bexec
#bexec export VERSION=1.11 OS=linux ARCH=amd64 && \
#        wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz && \
#        sudo tar -C /usr/local -xzvf go$VERSION.$OS-$ARCH.tar.gz && \
#        rm go$VERSION.$OS-$ARCH.tar.gz

#bexec echo 'export GOPATH=${HOME}/go' >> ~/.bashrc && \
#        echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc         && \ 
#        source ~/.bashrc

#bexec go get -u github.com/golang/dep/cmd/dep
